import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import FurnishopLogo from '../public/furnishop-logo.png'
import SearchIcon from '../public/search.png'
import MoreIcon from '../public/more.png'
import DealsIcon from '../public/deals-icon.png'
import Illustration1 from '../public/illustration1.png'
import Illustration2 from '../public/illustration2.png'
import Illustration3 from '../public/illustration3.png'
import Illustration4 from '../public/illustration4.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Noto+Serif+JP:wght@700&family=Open+Sans:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      
      <main className={`flex flex-col`}>
        <header className={`flex flex-col h-screen`}>
          <navbar className={`flex my-8 items-center`}>
            <ul className={`flex flex-row px-24 justify-between items-center w-full`}>
              <li>
                <Image
                  src={FurnishopLogo}
                  width={`133`}
                  height={`37`}
                  alt={``}
                >
                </Image>
              </li>
              <li className={`w-3/6`}>
                <ul className={`flex flex-row justify-around w-full font-monts font-medium text-blacko2`}>
                  <Link href={`#`}>
                    <a>
                      <li>Home</li>
                    </a>
                  </Link>
                  <Link href={`#`}>
                    <a>
                      <li>About</li>
                    </a>
                  </Link>
                  <Link href={`#`}>
                    <a>
                      <li>Features</li>
                    </a>
                  </Link>
                  <Link href={`#`}>
                    <a>
                      <li>Contact</li>
                    </a>
                  </Link>
                </ul>
              </li>
              <li>
                <ul className={`flex flex-row gap-11`}>
                  <li>
                    <Image
                      src={SearchIcon}
                      width={`20`}
                      height={`20`}
                      className={`cursor-pointer`}
                      alt={``}
                    >
                    </Image>
                  </li>
                  <li>
                    <Image
                      src={MoreIcon}
                      width={`19`}
                      height={`14`}
                      className={`cursor-pointer`}
                      alt={``}
                    >
                    </Image>
                  </li>
                </ul>
              </li>
            </ul>
          </navbar>
          <div className={`bg-green-200 h-full`}>
            Ici suite du header
          </div>
        </header>
        <section1 className={`flex flex-col h-52 justify-center items-center gap-y-10 bg-light-grey`}>
          <h2 className={`font-opsans font-medium text-dark-blue text-xl`}>TRUSTED BY OVER 1K+ COMPANIES</h2>
          <ul className={`flex flex-row w-full justify-around px-40 text-xl uppercase`}>
            <li>
              Company 1
            </li>
            <li>
              Company 2
            </li>
            <li>
              Company 3
            </li>
            <li>
              Company 4
            </li>
            <li>
              Company 5
            </li>
          </ul>
        </section1>
        <section2 className={`flex flex-row h-h-screen px-28 items-center justify-between`}>
          <div className={`flex flex-col w-3/5 gap-y-5`}>
            <h2 className={`font-noto text-5xl text-green-cyan`}>Hot 🔥<br/>deals for you</h2>
            <p className={`text-dark-grey`}>Online shopping for retail sales<br/>direct to consumers</p>
          </div>
          <div className={`flex flex-row justify-between gap-x-6`}>
            <div className={`flex flex-col gap-y-7`}>
              <div>
                <Image
                  src={DealsIcon}
                  width={`32`}
                  height={`35`}
                  alt={``}
                />
              </div>
              <p className={`font-opsans font-bold text-xl`}>1.5% cashback</p>
              <p className={`text-dark-grey`}>Online shopping for retail sales direct to consumers</p>
            </div>
            <div className={`flex flex-col gap-y-7`}>
              <div>
                <Image
                  src={DealsIcon}
                  width={`32`}
                  height={`35`}
                  alt={``}
                />
              </div>
              <p className={`font-opsans font-bold text-xl`}>30-day terms</p>
              <p className={`text-dark-grey`}>Online shopping for retail sales direct to consumers</p>
            </div>
            <div className={`flex flex-col gap-y-7`}>
              <div>
                <Image
                  src={DealsIcon}
                  width={`32`}
                  height={`35`}
                  alt={``}
                />
              </div>
              <p className={`font-opsans font-bold text-xl`}>Save money</p>
              <p className={`text-dark-grey`}>Online shopping for retail sales direct to consumers</p>
            </div>
          </div>
        </section2>
        <section3 className={`flex flex-col px-36 gap-y-16 py-20`}>
          <div className={`flex flex-row justify-between`}>
            <div className={`w-1/3 flex flex-col gap-y-5`}>
              <h2 className={`font-noto text-5xl text-green-cyan `}>Abouts us</h2>
              <p className={`text-grey-blue`}>At Besnik Consultancy, we take pride in our values – service, integrity, and excellence.</p>
            </div>
            <div>
              <button className={`py-3 px-8 rounded-lg bg-light-grey text-dark-grey`}>Learn more</button>
            </div>
          </div>
          <div className={`flex flex-row`}>
            <ul className='flex flex-wrap w-1/2 gap-16'>
              <li className={`flex flex-col w-2/5 gap-y-1`}>
                <p className={`text-6xl font-bold font-opsans mb-7 text-green-cyan`}>1.</p>
                <p className={`text-xl font-bold text-green-cyan`}>Who We Are</p>
                <p className={`text-grey-blue`}>You get a 2-week free trial to kick the Smarty tries. We want you to.</p>
              </li>
              <li className={`flex flex-col w-2/5 gap-y-1`}>
                <p className={`text-6xl font-bold font-opsans mb-7 text-green-cyan`}>2.</p>
                <p className={`text-xl font-bold text-green-cyan`}>What Do We Do</p>
                <p className={`text-grey-blue`}>We give you a free course that guides you through the process.</p>
              </li>
              <li className={`flex flex-col w-2/5 gap-y-1`}>
                <p className={`text-6xl font-bold font-opsans mb-7 text-green-cyan`}>3.</p>
                <p className={`text-xl font-bold text-green-cyan`}>how Do We Help</p>
                <p className={`text-grey-blue`}>Use our multimedia lecturers, videos, and coaching sessions.</p>
              </li>
              <li className={`flex flex-col w-2/5 gap-y-1`}>
                <p className={`text-6xl font-bold font-opsans mb-7 text-green-cyan`}>4.</p>
                <p className={`text-xl font-bold text-green-cyan`}>Create success story</p>
                <p className={`text-dark-grey`}>Use our multimedia lecturers, videos, and coaching sessions.</p>
              </li>
            </ul>
            <div className={`flex flex-row gap-x-3 w-1/2 p-5`}>
              <div className={`flex flex-col gap-y-3`}>
                <div className={`pt-10`}>
                  <Image
                    src={Illustration1}
                    width=""
                    height=""
                  />
                </div>
                <div>
                  <Image
                    src={Illustration2}
                    width=""
                    height=""
                  />
                </div>
              </div>
              <div className={`flex flex-col gap-y-3`}>
                <div>
                  <Image
                    src={Illustration3}
                    width=""
                    height=""
                  />
                </div>
                <div>
                  <Image
                    src={Illustration4}
                    width=""
                    height=""
                  />
                </div>
              </div>
            </div>
          </div>
        </section3>
        <section4 className={``}>
          
        </section4>
        <footer className={styles.footer}>

        </footer>
      </main>
    </div>
  )
}
